"""Build the self-contained interactive HTML thesis report.

Reads:
  - results/dashboard_data.json  (generated by build_dashboard_data.py)
  - src/visualization/template.html
  - src/visualization/charts.js

Writes:
  - results/index.html  (single self-contained file)

Run:  python -m src.visualization.build_report
"""
import json
from pathlib import Path
import config


def build(results_dir: Path = None) -> Path:
    rd = results_dir or config.RESULTS_DIR
    here = Path(__file__).parent

    # Prefer the unified dashboard_data.json (includes ml + kp + all derived series)
    data_file = rd / "dashboard_data.json"
    if data_file.exists():
        payload = json.loads(data_file.read_text())
    else:
        # Fallback: assemble a minimal payload from ml_results + kpis
        ml = json.loads((rd / "ml_results.json").read_text())
        kp = json.loads((rd / "kpis.json").read_text())
        payload = {"ml": ml, "kp": kp,
                   "models_order": ["RandomForest", "StackingEnsemble", "XGBoost",
                                    "LightGBM", "GradientBoost", "SVR",
                                    "Traditional_ITU", "Traditional_Crane"]}

    template = (here / "template.html").read_text(encoding="utf-8")
    script   = (here / "charts.js").read_text(encoding="utf-8")

    html = (template
            .replace("/*__DATA__*/", json.dumps(payload))
            .replace("/*__SCRIPT__*/", script))

    out = rd / "index.html"
    out.write_text(html, encoding="utf-8")
    print(f"[build_report] wrote {out}  ({out.stat().st_size/1024:.1f} KB)")
    return out


if __name__ == "__main__":
    build()
